import{a as y,S as L,i as l}from"./assets/vendor-DDdXnYQq.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const b="https://pixabay.com/api/",v="51739132-2493f22fabb11ebba5692bb32",w=15;async function S(o,n=1){const s={key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:w};return(await y.get(b,{params:s})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader-form"),g=document.querySelector(".loader-more"),p=document.querySelector(".load-more");function q(o){const n=o.map(({webformatURL:s,largeImageURL:r,tags:e,likes:t,views:c,comments:d,downloads:u})=>`
    <li class="gallery-item">
      <a href="${r}">
        <img src="${s}" alt="${e}" loading="lazy" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${t}</p>
        <p><b>Views:</b> ${c}</p>
        <p><b>Comments:</b> ${d}</p>
        <p><b>Downloads:</b> ${u}</p>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",n)}function E(){m.innerHTML=""}function P(o="form"){o==="form"&&h.classList.remove("hidden"),o==="more"&&g.classList.remove("hidden")}function M(o="form"){o==="form"&&h.classList.add("hidden"),o==="more"&&g.classList.add("hidden")}function B(){p.classList.remove("hidden")}function f(){p.classList.add("hidden")}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".form"),n=document.querySelector(".load-more");let s="",r=1,e=0;const t=15,c=new L(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});o.addEventListener("submit",async a=>{if(a.preventDefault(),s=a.currentTarget.elements["search-text"].value.trim(),!s){l.warning({message:"Please enter a search term"});return}r=1,E(),f(),await d("form")}),n.addEventListener("click",async()=>{f(),await d("more")});async function d(a){try{P(a);const i=await S(s,r);if(!i.hits||i.hits.length===0){r===1?l.info({message:"No images found, try another query."}):l.info({message:"You've reached the end of search results."});return}q(i.hits),c.refresh(),e=i.totalHits,r*t<e?B():(f(),l.info({message:"You've reached the end of search results."})),r+=1,u()}catch(i){console.error(i),l.error({message:"Something went wrong. Try again later."})}finally{M(a)}}function u(){const a=document.querySelector(".gallery li");if(!a)return;const{height:i}=a.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}});
//# sourceMappingURL=index.js.map
